#goal/Parameters
geometry_msgs/PoseStamped coord
string type
string direction
bool obj_reach
bool gripper_content
bool screwable

---
#result
geometry_msgs/PoseStamped final_coord

---
#feedback
string movement
